apiVersion: v1
appVersion: ""
description: rbac-operator manages authorization for OIDC enabled control-plane Kubernetes APIs.
icon: https://s.giantswarm.io/app-icons/rbac-bootstrap/1/light.svg
home: https://github.com/giantswarm/rbac-operator
name: rbac-operator
version: "0.42.3"
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: shield
